version: '3.8'

services:
  monolito-app:
    image: monolito-app
    container_name: monolito-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://monolito-db:5432/edugo
      SPRING_DATASOURCE_USERNAME: ricajust
      SPRING_DATASOURCE_PASSWORD: '123'
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: microsservico
      SPRING_RABBITMQ_PASSWORD: microsservico123
    depends_on:
      monolito-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - edugo_tcc_net

  monolito-db:
    image: monolito-db
    container_name: monolito-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ricajust
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: edugo
    volumes:
      - monolito_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ricajust -d edugo"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - edugo_tcc_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=microsservico
      - RABBITMQ_DEFAULT_PASS=microsservico123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - edugo_tcc_net

volumes:
  monolito_db_data:

networks:
  edugo_tcc_net:
    driver: bridge